### PR TITLE
Write populate blueprint

### PR DESCRIPTION
**Pull request by GoldenChrysus**
Performing a GET populate request (e.g. /\<model>/:parentid/<relationship_attribute>/:id) is currently returned as 501, not implemented. This change implements it.

### CODE REVIEW

**Comment by dynamiccast** [comment]
Hi @GoldenChrysus and thank you for your contribution ! Sorry I review it just now.
- So a recent change on master conflicted your PR. It seems like it's just a matter on moving your code down the file to make room for the new tests introduced in #50.
- Also, do you think you could edit your files to adapt the the project's indentation ? I am sorry the guidelines aren't clear about that. Comments are fine but aligning equal signes and indenting with tabs do not go along with the rest of the project.
- I understand you disabled auto dating on your test for the involved model and this is fine because `created-at` and `updated-at` are tested on the Post model. However, why have you explicitly set `pluralize: true` in the blueprint config ? This is automatically done in the module's hook.

**Comment by GoldenChrysus** [comment]
If I recall correctly, I ran into an issue in my tests where I was getting a 404 because it was attempting to access non-pluralized URL's in the API. I will resolve all the other issues this weekend.

**Comment by GoldenChrysus** [comment]
(Note that this commit hasn't fixed the formatting yet. This was only for the test case.)

**Comment by GoldenChrysus** [comment]
Hey @dynamiccast. Can you review this again to see if the formatting is now correct?

**Comment by dynamiccast** [comment]
@GoldenChrysus Perfect ! Thanks for your work !

**Pull request merged**
