### PR TITLE
basic filtering support on find

### PR DESCRIPTION
**Pull request by leojpod**
Add tests and implementation for basic filtering

i.e.: 
`GET /users?filter[email]=john.doe@something.com` will return the users whose email are `john.doe@something.com`

### CODE REVIEW

**Comment by dynamiccast** [comment]
Fixes https://github.com/dynamiccast/sails-json-api-blueprints/issues/44

**Comment by dynamiccast** [comment]
I'm okay with the dummy's db to be wiped out when running `npm run tests`. However, can you update the README to specify this is now handled automatically ?

**Comment by dynamiccast** [comment]
I don't think we need to import the module `case-converter`. `JsonApiService` comes with a private method to change case on an Object's keys : https://github.com/dynamiccast/sails-json-api-blueprints/blob/master/lib/api/services/JsonApiService.js#L113
Calling `JsonApiService::deserializer` (https://github.com/dynamiccast/sails-json-api-blueprints/blob/master/lib/api/services/JsonApiService.js#L166) does the job in addition to handling any other case format for Model's attributes. See (https://github.com/dynamiccast/sails-json-api-blueprints#have-a-different-sails-models-attributes-keys-case-than-json-payload).

I create this patch to demonstrate your new tests still pass. Can you check it still work the way you want ?

```
From 49ff5eee0bbb252e36791e03166725199635c5b0 Mon Sep 17 00:00:00 2001
From: Olivier Berthonneau <berthonneau.olivier@gmail.com>
Date: Mon, 23 Jan 2017 10:12:09 -0800
Subject: [PATCH] Use default deserializer

---
 lib/api/blueprints/find.js | 3 +--
 package.json               | 1 -
 2 files changed, 1 insertion(+), 3 deletions(-)

diff --git a/lib/api/blueprints/find.js b/lib/api/blueprints/find.js
index 516de25..01cd886 100644
--- a/lib/api/blueprints/find.js
+++ b/lib/api/blueprints/find.js
@@ -2,7 +2,6 @@
  * Module dependencies
  */
 var actionUtil = require('./_util/actionUtil');
-var  caseConverter = require('case-converter')
 /**
  * Find Records
  *
@@ -20,7 +19,7 @@ module.exports = function findRecords(req, res) {

   // Lookup for records that match the specified criteria

-  var queryParams = caseConverter.toCamelCase(req.query.filter)
+  var queryParams = JsonApiService.deserialize(req.query.filter) || null;

   var query = Model.find(queryParams);

diff --git a/package.json b/package.json
index 6cdce6f..8de1f44 100644
--- a/package.json
+++ b/package.json
@@ -25,7 +25,6 @@
   },
   "homepage": "https://github.com/dynamiccast/sails-json-api-blueprints#readme",
   "dependencies": {
-    "case-converter": "^1.0.1",
     "json-api-serializer": "1.1.2",
     "jsonapi-validator": "^2.0.0",
     "lodash": "^4.13.1",
--
2.11.0
```

**Comment by leojpod** [comment]
Nice, I applied the patch and it works nicely. 
I'll edit the readme quickly.

**Comment by dynamiccast** [comment]
Thanks for you contribution !

**Comment by leojpod** [comment]
De rien :smile:

**Pull request merged**
