### PR TITLE
Slighly more advance filtering

### PR DESCRIPTION
**Pull request by leojpod**
This PR allows to use more complex `filter[prop]=` thingy and leverage the sails ORM directly. 
As the JSONAPI guidelines are rather vague on that point, I don't see why not using the sails API syntex directly 😄

### CODE REVIEW

**Comment by dynamiccast** [comment]
Hi @leojpod and thank you for your contribution. I really don't use sails.js anymore and cannot maintain this repository anymore.
Feel free to fork this repo where you will be able to publish your update.

**Comment by leojpod** [comment]
Hi @dynamiccast ! 
Thanks for the quick update. 
I still have one project on sails 0.12 that I need to upgrade at some point :x 
Just out of curiosity, what are you using for backend project?

**Comment by leojpod** [comment]
Could you give me access to the npm package so I can publish an update?

**Comment by dynamiccast** [comment]
@leojpod You know have pushing rights to npm and this repo on Github. Keep up the good work!
I originally created the project for Nanocloud, a company I use to work for: https://github.com/Nanocloud/nanocloud
For backend projects, I have a simple koa server and I use sequelize to connect to the database. I found sails.js to be "too much" for most application.

**Comment by leojpod** [comment]
Thanks! I'll look into merging that and pushing a new version out soon 😄 

I've never used Koa, I should check it out. I agree about sails being too much, although the sails v1 sounds a bit better for that matter. 
That being said, I mostly consider sails as an express server with some added conventions and sometimes that's an efficient way to get things up and running fast :) 
I'm looking into Nestjs as a potential next framework for the backend (although truth be told, I'd like to do some Haskell for my next backend project :smile: )

**Pull request merged**
