### PR TITLE
support for include

### PR DESCRIPTION
**Pull request by leojpod**
Implementation of #46

### CODE REVIEW

**Comment by leojpod** [comment]
@dynamiccast Do you have a moment to review that?

**Comment by dynamiccast** [comment]
I'm sorry for the delay here.
Can you add a test for the `findOne` blueprint as well ? Even though it forwards to `actionUtil.populateEach`like `find`, it would be better to have a dedicated test in case the implementations diverge in the future.

**Comment by leojpod** [comment]
Sure thing, I'll write that up whenever I get a minute :)

**Comment by dynamiccast** [comment]
Closed in favor of updated #50

**Pull request closed without merging**
